# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Flutter build
variables:
  projectDirectory: 'azure_devops_into'
trigger:
- master
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
  - job: iOS
    pool:
      vmImage: 'macOS-latest'